name: manual-test

on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Folder to run tests from'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - cart
          - checkout

jobs:
  manual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          playwright install

      - name: Run tests with Allure
        run: |
          if [ "${{ github.event.inputs.folder }}" == "all" ]; then
            pytest --alluredir=allure-results
          else
            pytest tests/${{ github.event.inputs.folder }} --alluredir=allure-results
          fi

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

    #   - name: Download Allure CLI
    #     run: |
    #       wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
    #       tar -zxvf allure-2.13.8.tgz

    #   - name: Generate Allure report
    #     run: |
    #       ./allure-2.13.8/bin/allure generate allure-results --clean -o allure-report

    #   - name: Upload Allure report
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: allure-report
    #       path: allure-report